#' workflow_main
#' main workflow loop
#'
#' @return NULL, never
#'
workflow_main <- function() {
  flows <- flows_parse()

  flows_update_status
}

#' flows_update_status
#'
#' @param flows data.table of flows
#'
#' @return data.table of flows with added columns:
#' - prev_scheduled_run: POSIXct previous scheduled run time, generated by parse_cron from on.schedule
#' - next_scheduled_run: POSIXct next scheduled run time, generated by parse_cron from on.schedule
#' - last_start: POSIXct last start time, updated when task is run
#' - last_end: POSIXct last end time, updated when task is completed or by flow_get_last_run
#' - status: string (`Waiting`,`Running`,`Finished`)
#' - retval: integer return value, or NA if not yet `Finished`
#'
#' @importFrom checkmate assert_data_table
#'
flows_update_status <- function(flows) {
  status <- scheduled_runs <- on.schedule <- NULL  

  assert_data_table(flows)

  # Startup logic
  if (is.null(flows$status)) {
    flows[, `:=`(
      status = "Waiting",
      retval = NA_integer_,
      scheduled_runs = NA,
      last_start = as.POSIXct(NA),
      last_end = as.POSIXct(NA)
    )]
  }

  flows[
    status == "Waiting",
    scheduled_runs := lapply(on.schedule, lapply, parse_cron)
  ]

  # flows[status=="Waiting" & is.na(last_end),
  #       last_end:=flow_get_last_run(name)]

  flows
}
